spring:
  jpa:
    generate-ddl=true:
    hibernate:
      ddl-auto=create-drop:h2:
    console:
      enabled: true
      path: /h2
  datasource:
    platform: postgres
    url: ${SICOCEL_URL}
    username:  ${SICOCEL_USER}
    password:  ${SICOCEL_PASS}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: 'classpath:db/databaseChangeLog.yaml'